import type { Metadata } from "next";
import { Inter,Plus_Jakarta_Sans } from "next/font/google";
import "./styles/globals.css";
import Header from "@/components/navbar/_header";
import Footer from "@/components/footer/_footer";

const inter = Inter({ subsets: ["latin"] });
const plusJakarta = Plus_Jakarta_Sans({ 
  subsets: ["latin"],
  weight : ["300","500","700","800"],
  variable: "--font-plus-jakarta-sans"
});

export const metadata: Metadata = {
  title: "Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className},${plusJakarta.className}`}>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
