import React from 'react'
import { Metadata } from 'next';
import WeclomeSection from '@/components/welcome/welcome'

export const metadata: Metadata = {
    title: "FilmKu",
    description: "Generated by create next app",
};

function Dashboard() {
    return (
        <section className="w-full h-screen">
            <div className="max-w-screen-2xl mx-auto">
                <div className="relative">
                    <WeclomeSection/>
                    <div className="bg-[#7c491f] absolute top-[15rem] -z-10 hidden lg:block right-[45rem] h-[31.25rem] w-[31.25rem] rounded-full blur-[10rem] sm:w-[68.75rem]"></div>
                    <div className="bg-[#2c2b2a] absolute top-[15rem] -z-10 hidden lg:block left-[-55rem] h-[31.25rem] w-[50rem] rounded-full blur-[10rem] sm:w-[68.75rem] md:left-[-33rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem]"></div>
                    <div className="bg-[#2c2b2a] absolute top-[-9rem] -z-10 right-[2%] h-[50rem] w-[50rem] rounded-full sm:w-[68.75rem] md:left-[-33rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem] visible md:hidden"></div>
                </div>
            </div>
        </section>
    )
}

export default Dashboard